# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_and_deploy_production:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          key: v1-dependencies-

      - run: 
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: test
          command: echo "no tests"

      - run:
          name: build
          command: npm run build    

      - run:
          name: Install awscli
          command: |
            sudo apt-get -y -qq install awscli
      - run: 
          name: deploy to production
          command: aws s3 sync public s3://khaledgarbaya.net --region us-west-2 --delete --cache-control "max-age=3153600"
      - run:
          name: Enable cloudfront feature
          command: aws configure set preview.cloudfront true
      - run:
          name: Enable cloudfront feature
          command: aws configure set preview.create-invalidation true 
      - run: 
          name: cloudfron Invalidation
          command: aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_INSTANCE --paths /*
  build_and_deploy_preview:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          key: v1-dependencies-

      - run: 
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: test
          command: echo "no tests"

      - run:
          name: build
          command: npm run build    

      - run:
          name: Install awscli
          command: |
            sudo apt-get -y -qq install awscli
      - run:
          name: Enable cloudfront feature
          command: aws configure set preview.cloudfront true
      - run:
          name: Enable cloudfront feature
          command: aws configure set preview.create-invalidation true 
      - run: 
          name: deploy to production
          command: aws s3 sync public s3://preview.khaledgarbaya.net --region us-west-2 --delete --cache-control "max-age=3153600"
workflows:
  version: 2
  build-deploy-production:
    jobs:
      - build_and_deploy_production:
          filters:
            branches:
              only: master
  build-deploy-preview:
    jobs:
      - build_and_deploy_preview:
          filters:
            branches:
              ignore: master
